name: health check schedule

on:
  schedule:
    - cron: '00 * 25 7 *'

jobs: 
  health_check:
    runs-on: ubuntu-latest
    steps: 
      - name: check the url
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-ci-cd.onrender.com
          max-attempts: 2
          retry-delay: 5s 