
name: NOtification test

on:
  push:
    branches:
      - dev

jobs:
  notification_job:
    runs-on: ubuntu-latest
    steps:
      - name: try discord message
        uses: sarisia/actions-status-discord@v1
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            nodetail: true
            title: "test  sarisia/actions-status-discord@v1"
      - name: Discord notification fail
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
            text: test rjstone/discord-webhook
            severity: error
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}