name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  context_test_job:
    runs-on: ubuntu-latest
    env: 
      COMMIT_MESSAGE: ${{ contains(join(github.event.commits.*.message), '#skip') }}
    steps: 
      - uses: actions/checkout@v4
      - name: github context
        run: echo "$COMMIT_MESSAGE"
      - name: test if
        if: env.COMMIT_MESSAGE == 'true'
        run: echo "COMMIT_MESSAGE true"
      - name: test if not
        if: env.COMMIT_MESSAGE != 'true'
        run: echo "COMMIT_MESSAGE nottrue"