name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  context_test_job:
    runs-on: ubuntu-latest
    env: 
      COMMIT_MESSAGE: ${{ toJson(github.event.commits.*.message).join(',') }}
    steps: 
      - uses: actions/checkout@v4
      - name: github context
        run: echo "$COMMIT_MESSAGE"